--------------------------------------------------------
--  DDL for Table ACCIDENTES
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."ACCIDENTES" 
   (    "ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER  NOCYCLE  NOKEEP  NOSCALE , 
    "FECHA" DATE, 
    "HORA" VARCHAR2(10 BYTE), 
    "DIRECCION" VARCHAR2(150 BYTE), 
    "COMUNA" VARCHAR2(50 BYTE), 
    "CIRCUNSTANCIA" VARCHAR2(100 BYTE), 
    "LUGAR" VARCHAR2(100 BYTE), 
    "CLASIFICACION" VARCHAR2(50 BYTE), 
    "TIPO" VARCHAR2(50 BYTE), 
    "MEDIO_PRUEBA" VARCHAR2(50 BYTE), 
    "DETALLES" VARCHAR2(4000 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.ACCIDENTES
SET DEFINE OFF;

--------------------------------------------------------
--  DDL for Index ACCIDENTES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."ACCIDENTES_PK" ON "SYSTEM"."ACCIDENTES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  
--------------------------------------------------------
--  Constraints for Table ACCIDENTES
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."ACCIDENTES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ACCIDENTES" MODIFY ("FECHA" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ACCIDENTES" MODIFY ("HORA" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ACCIDENTES" MODIFY ("DIRECCION" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ACCIDENTES" MODIFY ("COMUNA" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ACCIDENTES" MODIFY ("CIRCUNSTANCIA" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ACCIDENTES" MODIFY ("LUGAR" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ACCIDENTES" MODIFY ("DETALLES" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ACCIDENTES" MODIFY ("CLASIFICACION" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ACCIDENTES" MODIFY ("TIPO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ACCIDENTES" MODIFY ("MEDIO_PRUEBA" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ACCIDENTES" ADD CONSTRAINT "ACCIDENTES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
