  CREATE TABLE "SYSTEM"."EMPLEADORES" 
   (    "ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
    "NOMBRE" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
    "RUT" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
    "DIRECCION" VARCHAR2(150 BYTE) NOT NULL ENABLE, 
    "TELEFONO" VARCHAR2(25 BYTE) NOT NULL ENABLE, 
    "ACTIVIDAD_ECONOMICA" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
    "TRABAJADORES" NUMBER NOT NULL ENABLE, 
    "PROPIEDAD" VARCHAR2(25 BYTE) NOT NULL ENABLE, 
    "TIPO_EMPRESA" VARCHAR2(150 BYTE) NOT NULL ENABLE, 
     CONSTRAINT "EMPLEADORES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  
  CREATE TABLE "SYSTEM"."TRABAJADORES" 
   (    "ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
    "NOMBRES" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
    "APELLIDO_PATERNO" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
    "APELLIDO_MATERNO" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
    "DIRECCION" VARCHAR2(150 BYTE) NOT NULL ENABLE, 
    "TELEFONO" VARCHAR2(25 BYTE) NOT NULL ENABLE, 
    "RUN" VARCHAR2(25 BYTE) NOT NULL ENABLE, 
    "GENERO" VARCHAR2(25 BYTE) NOT NULL ENABLE, 
    "FECHA_NACIMIENTO" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
    "NACIONALIDAD" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
    "PROFESION" VARCHAR2(150 BYTE) NOT NULL ENABLE, 
    "TIPO_CONTRATO" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
    "EMPLEADOR_ID" NUMBER NOT NULL ENABLE, 
     CONSTRAINT "TRABAJADORES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
     CONSTRAINT "TRABAJADORES_FK1" FOREIGN KEY ("EMPLEADOR_ID")
      REFERENCES "SYSTEM"."EMPLEADORES" ("ID") ON DELETE SET NULL ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

  CREATE TABLE "SYSTEM"."ACCIDENTES" 
   (    "ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
    "FECHA" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
    "HORA" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
    "DIRECCION" VARCHAR2(150 BYTE) NOT NULL ENABLE, 
    "CIRCUNSTANCIA" VARCHAR2(150 BYTE) NOT NULL ENABLE, 
    "LUGAR" VARCHAR2(150 BYTE) NOT NULL ENABLE, 
    "DETALLES" CLOB NOT NULL ENABLE, 
    "CLASIFICACION" VARCHAR2(35 BYTE) NOT NULL ENABLE, 
    "TIPO" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
    "MEDIO_PRUEBA" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
    "CREADO" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
    "ACTUALIZADO" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
    "TRABAJADOR_ID" NUMBER NOT NULL ENABLE, 
    "EMPLEADOR_ID" NUMBER NOT NULL ENABLE, 
     CONSTRAINT "ACCIDENTES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
     CONSTRAINT "ACCIDENTES_FK1" FOREIGN KEY ("TRABAJADOR_ID")
      REFERENCES "SYSTEM"."TRABAJADORES" ("ID") ON DELETE SET NULL ENABLE, 
     CONSTRAINT "ACCIDENTES_FK2" FOREIGN KEY ("EMPLEADOR_ID")
      REFERENCES "SYSTEM"."EMPLEADORES" ("ID") ON DELETE SET NULL ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("DETALLES") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
